.pragma library

// AUTO-GENERATED by translate/generate_translations.py.
// Do not edit this file manually.

var catalogs = {
    "de": {
        "All": "Alle",
        "Files": "Dateien",
        "General": "Allgemein",
        "Language:": "Sprache:",
        "Log Out": "Abmelden",
        "No results found": "Keine Ergebnisse gefunden",
        "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.": "Keine Ergebnisse gefunden\n\n💡 Baloo durchsucht nur indizierte Ordner.\nPrüfe die Dateisuche unter Systemeinstellungen → Suche → Dateisuche.",
        "Pin": "Anheften",
        "Pinned": "Angeheftet",
        "Restart": "Neustart",
        "Search for apps, files and settings": "Nach Apps, Dateien und Einstellungen suchen",
        "Search results": "Suchergebnisse",
        "Settings": "Einstellungen",
        "Shut Down": "Beenden",
        "System default": "Systemstandard",
        "Unpin": "Von Angeheftet entfernen",
        "View: Grid  ▾": "Ansicht: Raster  ▾",
        "View: List  ▾": "Ansicht: Liste  ▾"
    },
    "en": {
        "All": "All",
        "Files": "Files",
        "General": "General",
        "Language:": "Language:",
        "Log Out": "Log Out",
        "No results found": "No results found",
        "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.": "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.",
        "Pin": "Pin",
        "Pinned": "Pinned",
        "Restart": "Restart",
        "Search for apps, files and settings": "Search for apps, files and settings",
        "Search results": "Search results",
        "Settings": "Settings",
        "Shut Down": "Shut Down",
        "System default": "System default",
        "Unpin": "Unpin",
        "View: Grid  ▾": "View: Grid  ▾",
        "View: List  ▾": "View: List  ▾"
    },
    "fr": {
        "All": "Tous",
        "Files": "Fichiers",
        "General": "Général",
        "Language:": "Langue :",
        "Log Out": "Se déconnecter",
        "No results found": "Aucun résultat trouvé",
        "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.": "Aucun résultat trouvé\n\n💡 Baloo recherche uniquement dans les dossiers indexés.\nVérifiez la recherche de fichiers dans Configuration du système → Recherche → Recherche de fichiers.",
        "Pin": "Épingler",
        "Pinned": "Épinglé",
        "Restart": "Redémarrer",
        "Search for apps, files and settings": "Rechercher des applications, des fichiers et des paramètres",
        "Search results": "Résultats de recherche",
        "Settings": "Paramètres",
        "Shut Down": "Éteindre",
        "System default": "Paramètre système",
        "Unpin": "Désépingler",
        "View: Grid  ▾": "Affichage : Grille  ▾",
        "View: List  ▾": "Affichage : Liste  ▾"
    },
    "it": {
        "All": "Tutti",
        "Files": "File",
        "General": "Generale",
        "Language:": "Lingua:",
        "Log Out": "Disconnetti",
        "No results found": "Nessun risultato trovato",
        "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.": "Nessun risultato trovato\n\n💡 Baloo cerca solo nelle cartelle indicizzate.\nControlla la ricerca dei file in Impostazioni di sistema → Cerca → Ricerca file.",
        "Pin": "Aggiungi ai preferiti",
        "Pinned": "Appuntati",
        "Restart": "Riavvia",
        "Search for apps, files and settings": "Cerca app, file e impostazioni",
        "Search results": "Risultati della ricerca",
        "Settings": "Impostazioni",
        "Shut Down": "Spegni",
        "System default": "Predefinito di sistema",
        "Unpin": "Rimuovi dai preferiti",
        "View: Grid  ▾": "Visualizzazione: Griglia  ▾",
        "View: List  ▾": "Visualizzazione: Elenco  ▾"
    },
    "nl": {
        "All": "Alles",
        "Files": "Bestanden",
        "General": "Algemeen",
        "Language:": "Taal:",
        "Log Out": "Afmelden",
        "No results found": "Geen resultaten gevonden",
        "No results found\n\n💡 Baloo only searches indexed folders.\nCheck file search under System Settings → Search → File Search.": "Geen resultaten gevonden\n\n💡 Baloo doorzoekt alleen geïndexeerde mappen.\nControleer Bestandszoeken via Systeeminstellingen → Zoeken → Bestandszoeken.",
        "Pin": "Vastmaken",
        "Pinned": "Vastgemaakt",
        "Restart": "Opnieuw opstarten",
        "Search for apps, files and settings": "Zoeken naar apps, bestanden en instellingen",
        "Search results": "Zoekresultaten",
        "Settings": "Instellingen",
        "Shut Down": "Afsluiten",
        "System default": "Systeemstandaard",
        "Unpin": "Losmaken",
        "View: Grid  ▾": "Weergave: Raster  ▾",
        "View: List  ▾": "Weergave: Lijst  ▾"
    }
};

function normalizeLocale(localeName) {
    if (!localeName) {
        return "en";
    }

    var normalized = String(localeName).replace("-", "_");
    var separator = normalized.indexOf("_");

    if (separator >= 0) {
        normalized = normalized.substring(0, separator);
    }

    return normalized.toLowerCase();
}

function translate(sourceText, selectedLanguage, systemLocale) {
    var language = selectedLanguage;

    if (!language || language === "system") {
        language = normalizeLocale(systemLocale);
    }

    var catalog = catalogs[language];

    if (catalog && catalog[sourceText] !== undefined && catalog[sourceText] !== "") {
        return catalog[sourceText];
    }

    return sourceText;
}
