#!/usr/bin/env python3
from pathlib import Path
import gettext
import json

translate_dir = Path(__file__).resolve().parent
package_root = translate_dir.parent
metadata = package_root / "metadata.json"

meta = json.loads(metadata.read_text(encoding="utf-8"))
plugin_id = meta["KPlugin"]["Id"]
domain = f"plasma_applet_{plugin_id}"

locale_root = package_root / "contents" / "locale"
output = package_root / "contents" / "ui" / "Translations.js"

catalogs = {}

for language_dir in sorted(locale_root.iterdir()):
    if not language_dir.is_dir():
        continue

    language = language_dir.name
    mo_file = language_dir / "LC_MESSAGES" / f"{domain}.mo"

    if not mo_file.is_file():
        continue

    with mo_file.open("rb") as handle:
        translations = gettext.GNUTranslations(handle)

    catalog = {}
    for key, value in translations._catalog.items():
        if not isinstance(key, str) or key == "":
            continue
        if not isinstance(value, str):
            continue
        catalog[key] = value

    catalogs[language] = catalog

js_catalogs = json.dumps(catalogs, ensure_ascii=False, indent=4, sort_keys=True)

content = """.pragma library

// AUTO-GENERATED by translate/generate_translations.py.
// Do not edit this file manually.

var catalogs = __CATALOGS__;

function normalizeLocale(localeName) {
    if (!localeName) {
        return "en";
    }

    var normalized = String(localeName).replace("-", "_");
    var separator = normalized.indexOf("_");

    if (separator >= 0) {
        normalized = normalized.substring(0, separator);
    }

    return normalized.toLowerCase();
}

function translate(sourceText, selectedLanguage, systemLocale) {
    var language = selectedLanguage;

    if (!language || language === "system") {
        language = normalizeLocale(systemLocale);
    }

    var catalog = catalogs[language];

    if (catalog && catalog[sourceText] !== undefined && catalog[sourceText] !== "") {
        return catalog[sourceText];
    }

    return sourceText;
}
""".replace("__CATALOGS__", js_catalogs)

output.write_text(content, encoding="utf-8")
print(f"[translations] Generated {output}")
